fullnameOverride: onenet
management:
  configmap: |-
    {
      "Stuns": [
        {
          "Proto": "udp",
          "URI": "{{ .STUN_SERVER }}",
          "Username": "",
          "Password": ""
        }
      ],
      "TURNConfig": {
        "TimeBasedCredentials": false,
        "CredentialsTTL": "12h0m0s",
        "Secret": "secret",
        "Turns": [
          {
            "Proto": "udp",
            "URI": "{{ .TURN_SERVER }}",
            "Username": "{{ .TURN_SERVER_USER }}",
            "Password": "{{ .TURN_SERVER_PASSWORD }}"
          }
        ]
      },
      "Relay": {
        "Addresses": ["rels://onenet.example.com:443/relay"],
        "CredentialsTTL": "24h",
        "Secret": "{{ .RELAY_PASSWORD }}"
      },
      "Signal": {
        "Proto": "https",
        "URI": "onenet.example.com:443",
        "Username": "",
        "Password": ""
      },
      "Datadir": "/var/lib/onenet/",
      "DataStoreEncryptionKey": "{{ .DATASTORE_ENCRYPTION_KEY }}",
      "HttpConfig": {
        "LetsEncryptDomain": "",
        "CertFile": "",
        "CertKey": "",
        "AuthAudience": "{{ .IDP_CLIENT_ID }}",
        "AuthIssuer": "https://idp.example.com/application/o/onenet/",
        "AuthUserIDClaim": "",
        "AuthKeysLocation": "https://idp.example.com/application/o/onenet/jwks/",
        "OIDCConfigEndpoint": "https://idp.example.com/application/o/onenet/.well-known/openid-configuration",
        "IdpSignKeyRefreshEnabled": false
      },
      "IdpManagerConfig": {
        "ManagerType": "authentik",
        "ClientConfig": {
          "Issuer": "https://idp.example.com/application/o/totmicro-traefik-onenet",
          "TokenEndpoint": "https://idp.example.com/application/o/token/",
          "ClientID": "{{ .IDP_CLIENT_ID }}",
          "ClientSecret": "",
          "GrantType": "client_credentials"
        },
        "ExtraConfig": {
          "Password": "{{ .IDP_SERVICE_ACCOUNT_PASSWORD }}",
          "Username": "{{ .IDP_SERVICE_ACCOUNT_USER }}"
        },
        "Auth0ClientCredentials": null,
        "AzureClientCredentials": null,
        "KeycloakClientCredentials": null,
        "ZitadelClientCredentials": null
      },
      "DeviceAuthorizationFlow": {
        "Provider": "hosted",
        "ProviderConfig": {
          "ClientID": "{{ .IDP_CLIENT_ID }}",
          "ClientSecret": "",
          "Domain": "idp.example.com",
          "Audience": "{{ .IDP_CLIENT_ID }}",
          "TokenEndpoint": "https://idp.example.com/application/o/token/",
          "DeviceAuthEndpoint": "https://idp.example.com/application/o/device/",
          "AuthorizationEndpoint": "",
          "Scope": "openid",
          "UseIDToken": false,
          "RedirectURLs": null
        }
      },
      "PKCEAuthorizationFlow": {
        "ProviderConfig": {
          "ClientID": "{{ .IDP_CLIENT_ID }}",
          "ClientSecret": "",
          "Domain": "",
          "Audience": "{{ .IDP_CLIENT_ID }}",
          "TokenEndpoint": "https://idp.example.com/application/o/token/",
          "DeviceAuthEndpoint": "",
          "AuthorizationEndpoint": "https://idp.example.com/application/o/authorize/",
          "Scope": "openid profile email offline_access api",
          "UseIDToken": false,
          "RedirectURLs": ["http://localhost:53000"]
        }
      },
      "StoreConfig": {
        "Engine": "postgres"
      },
      "ReverseProxy": {
        "TrustedHTTPProxies": null,
        "TrustedHTTPProxiesCount": 0,
        "TrustedPeers": null
      }
    }

  image:
    tag: 0.32.0
  persistentVolume:
    enabled: false
  envFromSecret:
    ONENET_STORE_ENGINE_POSTGRES_DSN: onenet/postgresDSN
    STUN_SERVER: onenet/stunServer
    TURN_SERVER: onenet/turnServer
    TURN_SERVER_USER: onenet/turnServerUser
    TURN_SERVER_PASSWORD: onenet/turnServerPassword
    RELAY_PASSWORD: onenet/relayPassword
    IDP_CLIENT_ID: onenet/idpClientID
    IDP_SERVICE_ACCOUNT_USER: onenet/idpServiceAccountUser
    IDP_SERVICE_ACCOUNT_PASSWORD: onenet/idpServiceAccountPassword
    DATASTORE_ENCRYPTION_KEY: onenet/datastoreEncryptionKey

signal:
  image:
    tag: 0.32.0

relay:
  image:
    tag: 0.32.0
  envFromSecret:
    ONET_AUTH_SECRET: onenet/relayPassword
  env:
    ONET_LOG_LEVEL: info
    ONET_LISTEN_ADDRESS: ":33080"
    ONET_EXPOSED_ADDRESS: rels://onenet.example.com:443/relay

dashboard:
  enabled: true
  image:
    tag: v2.9.0
  env:
    # Endpoints
    ONENET_MGMT_API_ENDPOINT: https://onenet.example.com:443
    ONENET_MGMT_GRPC_API_ENDPOINT: https://onenet.example.com:443
    # OIDC
    AUTH_CLIENT_SECRET:
    AUTH_AUTHORITY: https://idp.example.com/application/o/onenet/
    USE_AUTH0: false
    AUTH_SUPPORTED_SCOPES: openid profile email offline_access api
    AUTH_REDIRECT_URI:
    AUTH_SILENT_REDIRECT_URI:
    ONENET_TOKEN_SOURCE: accessToken
    NGINX_SSL_PORT:
    LETSENCRYPT_DOMAIN:
    LETSENCRYPT_EMAIL:
  envFromSecret:
    AUTH_CLIENT_ID: onenet/idpClientID
    AUTH_AUDIENCE: onenet/idpClientID

extraManifests:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: onenet-traefik
      labels:
        argocd.argoproj.io/instance: onenet-traefik
    spec:
      entryPoints:
      - websecure
      routes:
      - kind: Rule
        match: Host(`onenet.example.com`) && !PathPrefix(`/api`) && !PathPrefix(`/management`) && !PathPrefix(`/signalexchange`) && !PathPrefix(`/relay`)
        services:
        - name: onenet-traefik-dashboard
          namespace: onenet-traefik
          passHostHeader: true
          port: 80
      - kind: Rule
        match: Host(`onenet.example.com`) && PathPrefix(`/api`)
        services:
        - name: onenet-traefik-management
          namespace: onenet-traefik
          passHostHeader: true
          port: 80
      - kind: Rule
        match: Host(`onenet.example.com`) && PathPrefix(`/relay`)
        services:
        - name: onenet-traefik-relay
          namespace: onenet-traefik
          passHostHeader: true
          port: 33080
      - kind: Rule
        match: Host(`onenet.example.com`) && PathPrefix(`/management`)
        services:
        - name: onenet-traefik-management
          namespace: onenet-traefik
          passHostHeader: true
          port: 80
          scheme: h2c
      - kind: Rule
        match: Host(`onenet.example.com`) && PathPrefix(`/signalexchange`)
        services:
        - name: onenet-traefik-signal
          namespace: onenet-traefik
          passHostHeader: true
          port: 80
          scheme: h2c
      tls:
        secretName: onenet-tls
