{{- if .Values.management.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onenet.fullname" . }}-management
  namespace: {{ include "onenet.namespace" . }}
  labels:
    {{- include "onenet.management.labels" . | nindent 4 }}
data:
  management.json: |-
    {{- .Values.management.configmap | nindent 4 }}
{{- end -}}
