{{- if .Values.management.enabled -}}
{{- if .Values.management.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onenet.management.serviceAccountName" . }}
  namespace: {{ include "onenet.namespace" . }}
  labels:
    {{- include "onenet.management.labels" . | nindent 4 }}
  {{- with .Values.management.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
