{{- if .Values.management.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onenet.fullname" . }}-management
  namespace: {{ include "onenet.namespace" . }}
  labels:
    {{- include "onenet.management.labels" . | nindent 4 }}
  {{- with .Values.management.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: {{ .Values.management.service.name }}
      protocol: TCP
      name: {{ .Values.management.service.name }}
    {{- if .Values.management.metrics.enabled }}
    - port: {{ .Values.management.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "onenet.management.selectorLabels" . | nindent 4 }}
  {{- with .Values.management.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
