{{- if .Values.relay.enabled -}}
{{- if .Values.relay.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onenet.relay.serviceAccountName" . }}
  namespace: {{ include "onenet.namespace" . }}
  labels:
    {{- include "onenet.relay.labels" . | nindent 4 }}
  {{- with .Values.relay.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
