{{- if .Values.signal.enabled -}}

{{- if .Values.signal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onenet.signal.serviceAccountName" . }}
  namespace: {{ include "onenet.namespace" . }}
  labels:
    {{- include "onenet.signal.labels" . | nindent 4 }}
  {{- with .Values.signal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
