{{- range $k, $v := $.Values.ingress.policies }}
---
apiVersion: l1fe.network/v1
kind: ONETPolicy
metadata:
  finalizers:
    - l1fe.network/cleanup
  labels:
    app.kubernetes.io/component: operator
    {{- include "kubernetes-operator.labels" $ | nindent 4 }}
  name: {{ $k }}
spec:
  name: {{ $v.name }}
  sourceGroups:
  {{ toYaml $v.sourceGroups | nindent 4}}
  {{- if $v.description }}
  description: {{ $v.description }}
  {{- end }}
  {{- if $v.protocols }}
  protocols: {{ $v.protocols }}
  {{- end }}
  {{- if $v.ports }}
  ports: {{ $v.ports }}
  {{- end }}
  {{- if hasKey $v "bidirectional" }}
  bidirectional: {{ $v.bidirectional }}
  {{- end }}
{{- end }}