{{- if .Values.onenetAPI.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
stringData:
  ONET_API_KEY: {{ .Values.onenetAPI.key }}
{{- end }}